<img src="http://cfs22.simplicdn.net/ice9/new_logo.svgz "/>

# Assignment 01: Evaluate the Ad Budget Dataset of XYZ Firm

*The comments/sections provided are your cues to perform the assignment. You don't need to limit yourself to the number of rows/cells provided. You can add additional rows in each section to add more lines of code.*

*If at any point in time you need help on solving this assignment, view our demo video to understand the different steps of the code.*

**Happy coding!**

* * *

#### 1: Import the dataset

In [2]:
#Import the required libraries
import pandas as pd

In [3]:
#Import the advertising dataset
ad_data=pd.read_csv("Advertising Budget and Sales.csv")

#### 2: Analyze the dataset

In [4]:
#View the initial few records of the dataset
ad_data

Unnamed: 0  TV Ad Budget ($)  Radio Ad Budget ($)  \
0             1             230.1                 37.8   
1             2              44.5                 39.3   
2             3              17.2                 45.9   
3             4             151.5                 41.3   
4             5             180.8                 10.8   
..          ...               ...                  ...   
195         196              38.2                  3.7   
196         197              94.2                  4.9   
197         198             177.0                  9.3   
198         199             283.6                 42.0   
199         200             232.1                  8.6   

     Newspaper Ad Budget ($)  Sales ($)  
0                       69.2       22.1  
1                       45.1       10.4  
2                       69.3        9.3  
3                       58.5       18.5  
4                       58.4       12.9  
..                       ...        ...  
195                     13.8        7.6  
196                      8.1        9.7  
197                      6.4       12.8  
198                     66.2       25.5  
199                      8.7       13.4  

[200 rows x 5 columns]

In [7]:
#Check the total number of elements in the dataset
ad_data.size

1000

#### 3: Find the features or media channels used by the firm

In [8]:
#Check the number of observations (rows) and attributes (columns) in the dataset
ad_data.shape

(200, 5)

In [16]:
#View the names of each of the attributes
ad_data.columns

Index(['Unnamed: 0', 'TV Ad Budget ($)', 'Radio Ad Budget ($)',
       'Newspaper Ad Budget ($)', 'Sales ($)'],
      dtype='object')

#### 4: Create objects to train and test the model; find the sales figures for each channel

In [17]:
ad_new_data=ad_data.drop(['Unnamed: 0'], axis=1)

In [18]:
ad_new_data

TV Ad Budget ($)  Radio Ad Budget ($)  Newspaper Ad Budget ($)  Sales ($)
0               230.1                 37.8                     69.2       22.1
1                44.5                 39.3                     45.1       10.4
2                17.2                 45.9                     69.3        9.3
3               151.5                 41.3                     58.5       18.5
4               180.8                 10.8                     58.4       12.9
..                ...                  ...                      ...        ...
195              38.2                  3.7                     13.8        7.6
196              94.2                  4.9                      8.1        9.7
197             177.0                  9.3                      6.4       12.8
198             283.6                 42.0                     66.2       25.5
199             232.1                  8.6                      8.7       13.4

[200 rows x 4 columns]

In [20]:
#Create a feature object from the columns
feature= ad_data[['TV Ad Budget ($)','Radio Ad Budget ($)', 'Newspaper Ad Budget ($)']]

In [21]:
#View the feature object
feature

TV Ad Budget ($)  Radio Ad Budget ($)  Newspaper Ad Budget ($)
0               230.1                 37.8                     69.2
1                44.5                 39.3                     45.1
2                17.2                 45.9                     69.3
3               151.5                 41.3                     58.5
4               180.8                 10.8                     58.4
..                ...                  ...                      ...
195              38.2                  3.7                     13.8
196              94.2                  4.9                      8.1
197             177.0                  9.3                      6.4
198             283.6                 42.0                     66.2
199             232.1                  8.6                      8.7

[200 rows x 3 columns]

In [28]:
#Create a target object (Hint: use the sales column as it is the response of the dataset)
target=ad_new_data[['Sales ($)']]

In [29]:
#View the target object
target

Sales ($)
0         22.1
1         10.4
2          9.3
3         18.5
4         12.9
..         ...
195        7.6
196        9.7
197       12.8
198       25.5
199       13.4

[200 rows x 1 columns]

In [26]:
#Verify if all the observations have been captured in the feature object
feature.shape

(200, 3)

In [30]:
#Verify if all the observations have been captured in the target object
target.shape

(200, 1)

#### 5: Split the original dataset into training and testing datasets for the model

In [31]:
#Split the dataset (by default, 75% is the training data and 25% is the testing data)
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test= train_test_split(feature, target,random_state=1)

In [33]:
#Verify if the training and testing datasets are split correctly (Hint: use the shape() method)
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(150, 3)
(50, 3)
(150, 1)
(50, 1)


#### 6: Create a model  to predict the sales outcome

In [35]:
#Create a linear regression model
from sklearn.linear_model import LinearRegression
linReg=LinearRegression()
linReg.fit(x_train,y_train)

LinearRegression()

In [38]:
#Print the intercept and coefficients 
print (linReg.intercept_)
print (linReg.coef_)

[2.87696662]
[[0.04656457 0.17915812 0.00345046]]


In [40]:
#Predict the outcome for the testing dataset
y_pred=linReg.predict(x_test)
y_pred

array([[21.70910292],
       [16.41055243],
       [ 7.60955058],
       [17.80769552],
       [18.6146359 ],
       [23.83573998],
       [16.32488681],
       [13.43225536],
       [ 9.17173403],
       [17.333853  ],
       [14.44479482],
       [ 9.83511973],
       [17.18797614],
       [16.73086831],
       [15.05529391],
       [15.61434433],
       [12.42541574],
       [17.17716376],
       [11.08827566],
       [18.00537501],
       [ 9.28438889],
       [12.98458458],
       [ 8.79950614],
       [10.42382499],
       [11.3846456 ],
       [14.98082512],
       [ 9.78853268],
       [19.39643187],
       [18.18099936],
       [17.12807566],
       [21.54670213],
       [14.69809481],
       [16.24641438],
       [12.32114579],
       [19.92422501],
       [15.32498602],
       [13.88726522],
       [10.03162255],
       [20.93105915],
       [ 7.44936831],
       [ 3.64695761],
       [ 7.22020178],
       [ 5.9962782 ],
       [18.43381853],
       [ 8.39408045],
       [14

#### 7: Calculate the Mean Square Error (MSE)

In [41]:
#Import required libraries for calculating MSE (mean square error)
import numpy as np
from sklearn import metrics

In [42]:
#Calculate the MSE
print(np.sqrt(metrics.mean_squared_error(y_test,y_pred)))

1.404651423032895


In [45]:
print('True \n', y_test.values[0:10])
print()
print('Pred', y_pred[0:10])

True 
 [[23.8]
 [16.6]
 [ 9.5]
 [14.8]
 [17.6]
 [25.5]
 [16.9]
 [12.9]
 [10.5]
 [17.1]]

Pred [[21.70910292]
 [16.41055243]
 [ 7.60955058]
 [17.80769552]
 [18.6146359 ]
 [23.83573998]
 [16.32488681]
 [13.43225536]
 [ 9.17173403]
 [17.333853  ]]
